#ifndef SADLAYER_ERROR_H
#define SADLAYER_ERROR_H

typedef enum {
    SL_OK = 0,
    SL_ERROR_INVALID_ARGUMENT,
    SL_ERROR_IO,
    SL_ERROR_OUT_OF_MEMORY,
    SL_ERROR_TRUNCATED_FILE,
    SL_ERROR_BAD_DOS_SIGNATURE,
    SL_ERROR_BAD_PE_SIGNATURE,
    SL_ERROR_UNSUPPORTED_MACHINE,
    SL_ERROR_UNSUPPORTED_OPTIONAL_HEADER,
    SL_ERROR_INVALID_IMAGE,
    SL_ERROR_RVA_NOT_MAPPED,
    SL_ERROR_EXPORT_NOT_FOUND,
    SL_ERROR_MODULE_NOT_FOUND,
    SL_ERROR_DUPLICATE_MODULE,
    SL_ERROR_MODULE_REGISTRY_FULL,
    SL_ERROR_INVALID_FORWARDER,
    SL_ERROR_FORWARDER_LIMIT,
    SL_ERROR_ADDRESS_OUT_OF_RANGE,
    SL_ERROR_INVALID_ENCODING,
    SL_ERROR_BUFFER_TOO_SMALL,
    SL_ERROR_RELOCATION_REQUIRED,
    SL_ERROR_UNSUPPORTED_RELOCATION,
    SL_ERROR_MEMORY_MAPPING,
    SL_ERROR_MEMORY_PROTECTION,
    SL_ERROR_WX_CONFLICT,
    SL_ERROR_INVALID_STATE,
    SL_ERROR_PROCESS_CREATION,
    SL_ERROR_THREAD_ENVIRONMENT,
    SL_ERROR_WORKER_PROTOCOL,
    SL_ERROR_NOT_IMPLEMENTED
} sl_status;

const char *sl_status_string(sl_status status);

#endif
