#ifndef SADLAYER_ERROR_H
#define SADLAYER_ERROR_H

typedef enum {
    SL_OK = 0,
    SL_ERROR_INVALID_ARGUMENT,
    SL_ERROR_IO,
    SL_ERROR_OUT_OF_MEMORY,
    SL_ERROR_TRUNCATED_FILE,
    SL_ERROR_BAD_DOS_SIGNATURE,
    SL_ERROR_BAD_PE_SIGNATURE,
    SL_ERROR_UNSUPPORTED_MACHINE,
    SL_ERROR_UNSUPPORTED_OPTIONAL_HEADER,
    SL_ERROR_INVALID_IMAGE,
    SL_ERROR_RVA_NOT_MAPPED,
    SL_ERROR_NOT_IMPLEMENTED
} sl_status;

const char *sl_status_string(sl_status status);

#endif

